### ISSUE TITLE
Support alarms

### ISSUE THREAD

**Issue by simonvandel** [eldruin/ds323x-rs#2]
I could not find any way to program alarms in the docs. Is this feature planned?

I might try to contribute this back myself, but i'm just getting into embedded so it might take some time.

**Comment by eldruin** [comment]
I have already added support for the alarms although I have not published a new version yet. See [Changelog](https://github.com/eldruin/ds323x-rs/blob/master/CHANGELOG.md).
Do you need it urgently?

**Comment by simonvandel** [comment]
Urgently is a strong word. I was planning on playing around this weekend.

**Comment by eldruin** [comment]
Sure. I can publish a new version including alarm support today or tomorrow.

**Comment by simonvandel** [comment]
That would be great!

**Comment by eldruin** [comment]
Ok, I did some small improvements I had in the pipeline for this crate and just published version 0.2.0.
Please feel free to report any further issues, improvements or feedback.
Have fun!
