### ISSUE TITLE
Example using a microcontroller

### ISSUE THREAD

**Issue by David-OConnor** [eldruin/ds323x-rs#3]
For example, what would you replace
```rust
 let dev = hal::I2cdev::new("/dev/i2c-1").unwrap();
``` 
with when using the [stm32f3xx-hal](https://docs.rs/stm32f3xx-hal) crate instead? Probably something like `stm32f3xx_hal::stm32::I2C1{}`, but unable to get that working.

**Comment by eldruin** [comment]
Hi @David-OConnor,
There are several examples of using this crate in the [driver-examples](https://github.com/eldruin/driver-examples) repository which is linked in the documentation.
For the stm32f3 there are these two examples:
- [DS3231](https://github.com/eldruin/driver-examples/blob/master/stm32f3-discovery/examples/ds3231-f3.rs)
- [DS3234](https://github.com/eldruin/driver-examples/blob/master/stm32f3-discovery/examples/ds3234-f3.rs)

I am using the `f3` crate there and not `stm32f3xx-hal` but the changes should be trivial.
Please let me know if that works for you.

**Comment by David-OConnor** [comment]
Thank you very much - that clears things up entirely.

In this, case its turns out that you replace the original line with:
```rust
    let scl = gpiob.pb6.into_af4(&mut gpiob.moder, &mut gpiob.afrl);
    let sda = gpiob.pb7.into_af4(&mut gpiob.moder, &mut gpiob.afrl);

    let clocks = rcc.cfgr.freeze(&mut flash.acr);
    let i2c = hal::I2c::i2c1(dp.I2C1, (scl, sda), 100.khz(), clocks, &mut rcc.apb1);  // this line replaces the one in OP.
```
